#if UNITY_EDITOR
using Sirenix.OdinInspector;
using Sirenix.OdinInspector.Editor;
using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace Runestone.AesirInspector.OdinIntegration.Editor
{
    /// <summary>
    /// Odin 属性处理器：从源代码的 XML <c>/// &lt;summary&gt;</c> 注释自动生成 Inspector Tooltip。
    /// 如果成员已有 <see cref="TooltipAttribute"/> 或 <see cref="PropertyTooltipAttribute"/>，
    /// 则读取现有 Tooltip 值，追加自动生成的内容后动态替换原特性。
    /// </summary>
    public class OdinAutoTooltipAttributeProcessor : OdinAttributeProcessor<object>
    {
        /// <summary>
        /// 总开关。为 false 时处理器不执行任何操作——零开销。
        /// </summary>
        public static readonly bool ENABLED = true;

        /// <summary>
        /// 为 true 时从源代码的 <c>/// &lt;summary&gt;</c> 注释读取 Tooltip 文本。
        /// </summary>
        public static bool USE_SUMMARIES = true;

        /// <summary>
        /// 为 true 时，当找不到 summary 则使用成员名作为 Tooltip 回退。
        /// </summary>
        public static bool USE_MEMBER_NAME = true;

        /// <summary>
        /// 项目级跳过钩子。返回 true 则跳过该成员的自动 Tooltip 生成。
        /// </summary>
        public static Func<InspectorProperty, MemberInfo, List<Attribute>, bool> ShouldSkipMember;

        static readonly Dictionary<Type, Dictionary<string, string>> _summaryCache =
            new Dictionary<Type, Dictionary<string, string>>();

        static OdinAutoTooltipAttributeProcessor()
        {
            AssemblyReloadEvents.afterAssemblyReload += () => _summaryCache.Clear();
        }

        public override void ProcessChildMemberAttributes(InspectorProperty property, MemberInfo member, List<Attribute> attributes)
        {
            if (!ENABLED || (!USE_SUMMARIES && !USE_MEMBER_NAME))
                return;

            if (ShouldSkipMember != null && ShouldSkipMember(property, member, attributes))
                return;

            var autoTooltip = ResolveTooltipText(member);
            if (string.IsNullOrEmpty(autoTooltip))
                return;

            for (int i = 0; i < attributes.Count; i++)
            {
                if (attributes[i] is TooltipAttribute existingTooltip)
                {
                    attributes[i] = new TooltipAttribute(MergeTooltip(existingTooltip.tooltip, autoTooltip));
                    return;
                }

                if (attributes[i] is PropertyTooltipAttribute existingPropTooltip)
                {
                    attributes[i] = new PropertyTooltipAttribute(MergeTooltip(existingPropTooltip.Tooltip, autoTooltip));
                    return;
                }
            }

            attributes.Add(new TooltipAttribute(autoTooltip));
        }

        static string MergeTooltip(string existing, string autoGenerated) =>
            string.IsNullOrWhiteSpace(existing) ? autoGenerated : existing + "\n" + autoGenerated;

        static string ResolveTooltipText(MemberInfo member)
        {
            if (USE_SUMMARIES)
            {
                var summary = GetSummaryFromSource(member);
                if (!string.IsNullOrWhiteSpace(summary))
                    return summary;
            }

            return USE_MEMBER_NAME ? member.Name : null;
        }

        static string GetSummaryFromSource(MemberInfo member)
        {
            var declaringType = member.DeclaringType;
            if (declaringType == null)
                return null;

            if (!_summaryCache.TryGetValue(declaringType, out var memberSummaries))
            {
                memberSummaries = SourceSummaryParser.ParseSummariesForType(declaringType);
                _summaryCache[declaringType] = memberSummaries;
            }

            return memberSummaries != null && memberSummaries.TryGetValue(member.Name, out var summary)
                ? summary
                : null;
        }
    }
}
#endif
